// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using Yeelight_Control;
//
//    var yeelightControlDevice = YeelightControlDevice.FromJson(jsonString);

// https://app.quicktype.io?share=hW2Yil5tIJPxahgKHrjV
namespace Yeelight_Control.Helpers.YeelightDevices
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;
    using Yeelight_Control.Helpers;

    public partial class YeelightControlDevice
    {
        [JsonProperty("hostname")]
        public string Hostname { get; set; }
    }

    public partial class YeelightControlDevice
    {
        public static List<YeelightControlDevice> FromJson(string json) => JsonConvert.DeserializeObject<List<YeelightControlDevice>>(json, Converter.Settings);
    }
}
