// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using Yeelight_Control;
//
//    var yeelightPreset = YeelightPreset.FromJson(jsonString);

// https://app.quicktype.io?share=vz7DMmp5P9OCDuTqnhRh

namespace Yeelight_Control
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;
    using Yeelight_Control.Helpers;

    public partial class YeelightPreset
    {
        [JsonProperty("name")]
        public string Name { get; set; }

        [JsonProperty("bulbs")]
        public List<Bulb> Bulbs { get; set; }
    }

    public partial class Bulb
    {
        [JsonProperty("hostname")]
        public string Hostname { get; set; }

        [JsonProperty("color")]
        public YeelightColor Color { get; set; }

        [JsonProperty("brightness")]
        public int Brightness { get; set; }

        [JsonProperty("temperature", NullValueHandling = NullValueHandling.Ignore)]
        public int? Temperature { get; set; }

        [JsonProperty("power")]
        public bool Power { get; set; }
    }

    public partial class YeelightColor
    {
        [JsonProperty("r")]
        public int R { get; set; }

        [JsonProperty("g")]
        public int G { get; set; }

        [JsonProperty("b")]
        public int B { get; set; }
    }

    public partial class YeelightPreset
    {
        public static List<YeelightPreset> FromJson(string json) => JsonConvert.DeserializeObject<List<YeelightPreset>>(json, Converter.Settings);
    }

}
